### ISSUE TITLE
change fpga plugin from af mode to region mode

### ISSUE THREAD

**Issue by xxinran** [intel/intel-device-plugins-for-kubernetes#548]
First of all, I am not sure if this is an issue.  I'd like to state the case and have some discussion here.

I have deployed fpga plugin on af mode first,  and I can see there is fpga.intel.com/af-xxx in node's capacity.
And then I deleted the deamonset of af mode and re-deployed this DPI on region mode.  Here is my output:

```
Capacity:
...
fpga.intel.com/af-xxxxx:                   0
fpga.intel.com/region-xxxx:                1   
```

I am not sure if it is correct, or should we delete af-xxx `Capacity`, as well as the one in `Allocatable` section in node description?

**Comment by bart0sh** [comment]
@xxinran Thank you for reporting this. I don't think it's incorrect because amount of reported resources is 0, which reflects a reality. As far as I remember resources are checkpointed on the kubelet side. There is quite complex logic around old resources to ensure device persistence after node reboots. Anyway, my point is that as soon as old resources have 0 capacity and 0 allocatable number it's considered normal.
