### ISSUE TITLE
drop ubuntu-demo-opencl image

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#692]
it's somewhat outdated. we could drop it and simply use https://hub.docker.com/r/intelopencl/intel-opencl in `integpu-job.yaml` (`clinfo` or `clpeak`?)

/cc @eero-t @uniemimu what do you think?

**Comment by eero-t** [comment]
"clinfo" with OpenCL container is fine, and enough to test that GPU plugin works (running actual CL program, like earlier demo did, would test primarily drivers in the container, not the device plugin).

Maintainer of the image you linked is stated as "community user": https://hub.docker.com/u/intelopencl

Why there's no such (more lightweight) image under: https://hub.docker.com/u/intel ?

(And why e.g. all OneAPI ones are based on Ubuntu 18.04 and not something never with more up to date other SW available?)

PS. OpenCL is better test-case than media driver/SDK container, due to libva vs gpu-plugin issue: https://github.com/intel/libva/issues/540

(And for testing 3D, there would be a issue of getting headless 3D rendering.  One needs recent Weston for that in addition to 3D workload, as X server does not support headless HW accelerated rendering, and all reasonable 3D workloads available in distros require some display server.)
