### ISSUE TITLE
deployments: add Helm charts

### ISSUE THREAD

**Issue by mythi** [intel/intel-device-plugins-for-kubernetes#773]
Helm charts For SGX and operator.

**Comment by maxirus** [comment]
I built a Chart [here](https://github.com/maxirus/helm-charts/tree/master/charts/intel-gpu). Would like to contribute this Chart to this project so that it can be easily maintained along side the device plugin itself.

A prerequisite to this contribution is the maintainers of this repo will need to set up either an [Artifact Hub](https://artifacthub.io/) acct/repo, GitHub Pages + CI workflow, or some other hosting solution. Once complete, I will open a PR and deprecate mine.

**Comment by mythi** [comment]
@maxirus thanks!

We have Github Pages enabled so that can be used. However, I'd like to start with a Helm chart for the operator first. This is to reduce the maintenance burden of various deployment options.

**Comment by msivosuo** [comment]
Fixed by #981
