### ISSUE TITLE
Add devices to NFD

### ISSUE THREAD

**Issue by bart0sh** [intel/intel-device-plugins-for-kubernetes#872]
Instead of providing [NFD labelling rules](https://github.com/intel/intel-device-plugins-for-kubernetes/pull/871) we can add support of all our devices to NFD, so NFD would support them out of the box. 
This would simplify user experience as user would just need to install NFD to perform node labelling.

**Comment by mythi** [comment]
NFD does not maintain user configurations. We can have NFD installation and the rules creation in the same place so the user experience is not that different.

/cc @marquiz

**Comment by marquiz** [comment]
Yeah, we've been trying to keep vendor and use-case specific logic and all kinds of "device databases" etc out of NFD. I believe deployment of NFD labeling rules should now be easy enough as that can be done with just dropping one CR. So you could include e.g. the CR as part of the device plugin deployment(?)

One thing that is a bit cumbersome is enabling custom label namespaces (like `intel.com/<gpu-label>`). NFD now allows sub-namespaces of the default ns so you could use something like `intel.feature.node.kubernetes.io/<device-label>` in order to avoid customized NFD deployment.

**Comment by mythi** [comment]
> One thing that is a bit cumbersome is enabling custom label namespaces

Good that you mentioned it. We need a customized deployment ([SGX](https://github.com/intel/intel-device-plugins-for-kubernetes/blob/main/deployments/sgx_nfd/master-args.yaml#L3) so we could also look into clean labels like `sgx.intel.com: true` or something like that.

**Comment by bart0sh** [comment]
@marquiz thanks for the suggestion to use intel.feature.node.kubernetes.io/<device-label> format. I'll update #871 to use it.
